apiVersion: kubernetes.dask.org/v1
kind: DaskJob
metadata:  
  name: dask-job-4
  namespace: {{namespace}}
spec:
  job:
    spec:
      serviceAccountName: {{serviceAccountName}}
      nodeSelector:
        workload: apps
      containers:
        - name: job
          image: "{{image}}"
          imagePullPolicy: "IfNotPresent"
          args: {{formatted_args}}
          volumeMounts:
            - name: shared
              mountPath: /shared 
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{nfsname}}

  cluster:
    spec:
      worker:
        replicas: 3
        spec:
          nodeSelector:
            workload: apps
          containers:
            - name: worker
              image: "{{image}}"
              imagePullPolicy: "IfNotPresent"
              args:
                - dask-worker
                - --name
                - $(DASK_WORKER_NAME)
                - --dashboard
                - --dashboard-address
                - "8788"
              ports:
                - name: http-dashboard
                  containerPort: 8788
                  protocol: TCP
              env:
                - name: WORKER_ENV
                  value: hello-world # We dont test the value, just the name
      scheduler:
        spec:
          nodeSelector:
            workload: apps
          containers:
            - name: scheduler
              image: "{{image}}"
              imagePullPolicy: "IfNotPresent"
              args:
                - dask-scheduler
              ports:
                - name: tcp-comm
                  containerPort: 8786
                  protocol: TCP
                - name: http-dashboard
                  containerPort: 8787
                  protocol: TCP
              readinessProbe:
                httpGet:
                  port: http-dashboard
                  path: /health
                initialDelaySeconds: 5
                periodSeconds: 10
              livenessProbe:
                httpGet:
                  port: http-dashboard
                  path: /health
                initialDelaySeconds: 15
                periodSeconds: 20
              env:
                - name: SCHEDULER_ENV
                  value: hello-world
        service:
          type: ClusterIP
          selector:
            dask.org/cluster-name: dask-job
            dask.org/component: scheduler
          ports:
            - name: tcp-comm
              protocol: TCP
              port: 8786
              targetPort: "tcp-comm"
            - name: http-dashboard
              protocol: TCP
              port: 8787
              targetPort: "http-dashboard"
