[tool.poetry]
name = "dasf"
version = "1.0.beta.5"
description = "DASF is an Accelerated Framework for Machine Learning"
authors = ["Julio Faracco <jcfaracco@gmail.com>"]
maintainers = ["Julio Faracco <jcfaracco@gmail.com>"]
license = "MIT"
homepage = "https://github.com/lmcad-unicamp/dasf-core"
repository = "https://github.com/lmcad-unicamp/dasf-core"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Development Status :: 1 - Planning",
    "Environment :: GPU :: NVIDIA CUDA",
]
readme="README.md"
exclude = ["tests/*", "docs/*"]

[tool.poetry.dependencies]
dacite = "*"
dask = "*"
dask_cuda = "*"
dask_jobqueue = "*"
dask_memusage = "*"
dask_ml = "*"
dask-pytorch-ddp = "*"
GPUtil = "*"
gdown = "^4.6"
graphviz = "*"
h5py = "*"
hdbscan = "*"
ipympl = "*"
matplotlib = "*"
memray = "*"
networkx = "*"
ormsgpack = "*"
packaging = "*"
portalocker = "*"
protobuf = "~=3.20.1"
psutil = "*"
pyarrow = "*"
python = "^3.8"
pytorch-lightning = "*"
scikit-learn = "*"
torchvision = "*"
xarray = "*"
xgboost = "*"
zarr = "*"
xpysom-dask = { git = "https://github.com/jcfaracco/xpysom-dask.git@aa6fb025ae473fdbf0f4abb9c40a0272bfefc00b" }

#xpysom = { git = "https://github.com/jcfaracco/xpysom/", branch = "dask2" }

[tool.poetry.group.dev.dependencies]
black = "*"
coverage = "*"
flake8 = "*"
hpccm = "*"
mock = "*"
parameterized = "*"
pytest = "*"
pytest-cov = "*"
wheel = "*"

[tool.poetry.group.docs.dependencies]
sphinx = "*"
sphinx-autoapi = "*"
sphinx_rtd_theme = "*"
nbsphinx = "*"
pandoc = "*"

[tool.isort]
profile = "black"

[tool.coverage.paths]
source = ["dasf", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["dasf"]

[build-system]
requires = ["poetry-core>=1.1.10"]
build-backend = "poetry.core.masonry.api"
